export const appAction = {
  VERIFY_GUEST: 'VERIFY_GUEST',
  VERIFY_GUEST_SUCCESS: 'VERIFY_GUEST_SUCCESS',
};

export const userAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
};

export const modalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const eventAction = {
  GET_EVENTS: 'GET_EVENTS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',

  GET_EVENT_DETAIL: 'GET_EVENT_DETAIL',
  GET_EVENT_DETAIL_SUCCESS: 'GET_EVENT_DETAIL_SUCCESS',

  REGISTER_GUEST: 'REGISTER_GUEST',
  REGISTER_GUEST_SUCCESS: 'REGISTER_GUEST_SUCCESS',
};
