export const appAction = {
  TEST_PROMISE: 'TEST_PROMISE',
  TEST_PROMISE_SUCCESS: 'TEST_PROMISE_SUCCESS',
  TEST_PROMISE_FAILURE: 'TEST_PROMISE_FAILURE',
};

export const userAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
};

export const modalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const eventAction = {
  GET_EVENTS: 'GET_EVENTS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
};
