export const appAction = {
  TEST_PROMISE: 'TEST_PROMISE',
  TEST_PROMISE_SUCCESS: 'TEST_PROMISE_SUCCESS',
  TEST_PROMISE_FAILURE: 'TEST_PROMISE_FAILURE',
};

export const userAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};

export const modalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};
